In [37]:
import pandas as pd
import numpy as np

In [38]:
path = '../data/edos/train.csv'
df = pd.DataFrame(pd.read_csv(path))
df.head()

test_case    id   source language  \
0  EXIST2021  6978      gab       en   
1  EXIST2021  6979  twitter       en   
2  EXIST2021  6980  twitter       en   
3  EXIST2021  6981  twitter       en   
4  EXIST2021  6982  twitter       en   

                                                text       task1  \
0  Pennsylvania State Rep horrifies with opening ...  non-sexist   
1  @iilovegrapes He sounds like as ass and very c...  non-sexist   
2  @averyangryskel1 @4ARealistParty LOL! "This be...      sexist   
3  @WanderOrange @stalliontwink Rights?I mean yea...      sexist   
4  the jack manifold appreciation i’m seeing is o...  non-sexist   

                    task2  
0              non-sexist  
1              non-sexist  
2  ideological-inequality  
3  ideological-inequality  
4              non-sexist

In [39]:
df.loc[df["task1"] == "non-sexist", "task1"] = 0
df.loc[df["task1"] == "sexist", "task1"] = 1

In [40]:
df.task1.unique()

array([0, 1], dtype=object)

In [41]:
df['task2'].unique()

array(['non-sexist', 'ideological-inequality', 'objectification',
       'misogyny-non-sexual-violence', 'stereotyping-dominance',
       'sexual-violence'], dtype=object)

In [42]:
df.loc[df["task2"] == "non-sexist", "task2"] = 0

In [43]:
categories = df.task2.unique()
categories

array([0, 'ideological-inequality', 'objectification',
       'misogyny-non-sexual-violence', 'stereotyping-dominance',
       'sexual-violence'], dtype=object)

In [44]:
categories = np.delete(categories,np.argwhere(categories==0))
categories

array(['ideological-inequality', 'objectification',
       'misogyny-non-sexual-violence', 'stereotyping-dominance',
       'sexual-violence'], dtype=object)

In [45]:
categories.sort()
categories

array(['ideological-inequality', 'misogyny-non-sexual-violence',
       'objectification', 'sexual-violence', 'stereotyping-dominance'],
      dtype=object)

In [46]:
for i in range(0,len(categories)):
    df.loc[df["task2"] == categories[i], "task2"] = i+1

In [47]:
df.task2.unique()

array([0, 1, 3, 2, 5, 4], dtype=object)

In [48]:
path = "../data/train_int_label.csv"
df.to_csv(path, index=False)